Repository pinax-network/antelope-token-api, pull requests merged in 2024-05, with the labels that each got.

#21 Change generated dev tag to include timestamp
  .github/workflows/ghcr.yml
Labels: ops

#22 Update parameters name in query to match DB columns
  src/fetch/GET.ts
  src/queries.spec.ts
  src/queries.ts
Labels: bug

#23 Revert "Change generated dev tag to include timestamp (#21)"
  .github/workflows/ghcr.yml
Labels: bug, ops

#24 Fix OpenAPI example for `/transfers`
  src/fetch/openapi.ts
Labels: bug

#26 Fix Docker image tag labeling
  .github/workflows/ghcr.yml
Labels: ops

#25 Improve logging messages
  index.ts
  src/clickhouse/makeQuery.ts
  src/clickhouse/ping.ts
  src/fetch/GET.ts
  src/fetch/balance.ts
  src/fetch/head.ts
  src/fetch/health.ts
  src/fetch/openapi.ts
  src/fetch/supply.ts
  src/fetch/transfers.ts
  src/fetch/utils.ts
  src/logger.ts
  src/prometheus.ts
Labels: feature

#27 Throw error if the request page is beyond the total
  src/fetch/utils.spec.ts
  src/fetch/utils.ts
Labels: bug

#28 Have at least one `total_pages` in case of empty query result
  src/fetch/utils.spec.ts
  src/fetch/utils.ts
Labels: bug

#29 Refactor to use Typespec stack
  README.md
  bun.lockb
  index.ts
  package.json
  src/clickhouse/client.ts
  src/clickhouse/makeQuery.ts
  src/clickhouse/ping.ts
  src/config.ts
  src/fetch/GET.ts
  src/fetch/balance.ts
  src/fetch/head.ts
  src/fetch/health.ts
  src/fetch/openapi.ts
  src/fetch/supply.ts
  src/fetch/transfers.ts
  src/fetch/utils.spec.ts
  src/fetch/utils.ts
  src/logger.ts
  src/prometheus.ts
  src/queries.spec.ts
  src/queries.ts
  src/types.d.ts
  src/types/README.md
  src/types/api.ts
  src/types/zod.gen.ts
  src/typespec/README.md
  src/typespec/main.tsp
  src/typespec/models.tsp
  src/typespec/openapi3.tsp
  src/typespec/protobuf.tsp
  src/usage.ts
  src/utils.spec.ts
  src/utils.ts
  swagger/favicon.ico
  swagger/favicon.png
  swagger/index.html
  tsconfig.json
  tsp-output/@typespec/openapi3/openapi.json
  tsp-output/@typespec/protobuf/antelope/eosio/token/v1.proto
  tspconfig.yaml
Labels: documentation, ops, feature, major

#30 Move Typespec to devDependencies
  package.json
Labels: bug, minor

#31 Fill additional information to OpenAPI spec
  bun.lockb
  src/typespec/openapi3.tsp
  tsp-output/@typespec/openapi3/openapi.json
Labels: feature

#32 Fix pagination pages being parsed as strings
  index.ts
Labels: bug

#33 Drop FINAL requirement for `transfers` queries
  src/usage.ts
Labels: bug

#34 Fix wrong `extends` logic for `ValidUserParams`
  src/types/api.ts
Labels: bug

#35 Remove coercion for string parameters
  index.ts
Labels: bug

#36 Always use `transfers_block_num` for `transfers` by default
  src/usage.ts
Labels: bug
